version: "3.9"

x-common-env: &common_wordpress_env
  WP_ENVIRONMENT_TYPE: ${WP_ENVIRONMENT_TYPE:-production}

  # Need to specify, or else healthcheck will fail!!
  HEALTHZ_TOKEN: ${HEALTHZ_TOKEN}

  # WP core DB
  WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST:?mariadb host required}
  WORDPRESS_DB_USER: ${WORDPRESS_DB_USER:?db user required}
  WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD:?db pass required}
  WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME:-wordpress}

  # Redis (optional)
  # WP_REDIS_HOST:
  # WP_REDIS_PORT:
  # WP_REDIS_PREFIX:  # unique per site
  HEALTHZ_CHECK_REDIS: 0

  # S3 Uploads (keeps filesystem immutable)
  S3_UPLOADS_BUCKET: ${S3_UPLOADS_BUCKET:-}
  S3_UPLOADS_REGION: ${S3_UPLOADS_REGION:-}
  S3_UPLOADS_KEY: ${S3_UPLOADS_KEY:-}
  S3_UPLOADS_SECRET: ${S3_UPLOADS_SECRET:-}
  S3_UPLOADS_ENDPOINT: ${S3_UPLOADS_ENDPOINT:-}
  S3_UPLOADS_USE_PATH_STYLE_ENDPOINT: ${S3_UPLOADS_USE_PATH_STYLE_ENDPOINT:-true}

  # SMTP (optional)
  WP_SMTP_FORCE: ${WP_SMTP_FORCE:-false}
  SMTP_HOST: ${SMTP_HOST:-}
  SMTP_PORT: ${SMTP_PORT:-587}
  SMTP_USER: ${SMTP_USER:-}
  SMTP_PASSWORD: ${SMTP_PASSWORD:-}
  SMTP_SECURE: ${SMTP_SECURE:-tls}

  # Inject anything extra into wp-config via MU-plugin (last-wins)
  WORDPRESS_CONFIG_EXTRA: |
    define('WP_DEBUG', false);
    define('WP_HOME', getenv('WP_HOME') ?: 'https://${PRIMARY_DOMAIN}');
    define('WP_SITEURL', getenv('WP_SITEURL') ?: 'https://${PRIMARY_DOMAIN}');
    define('FORCE_SSL_ADMIN', true);
    define('DISABLE_WP_CRON', true);
  # define('WP_CACHE', true);  # enable for Redis
  # define('WP_MEMORY_LIMIT', '256M');

volumes:
  wp_vendor: {}        # read-only in app
  wp_content: {}
  # wp_files: {}         # optional; if you truly want immutable, avoid using this for uploads

services:
  # One-off vendor builder (runs fast then exits)
  vendor:
    # image: ghcr.io/kaffolder7/wp-vendor-builder:latest
    build:
      context: ./builder
    environment:
      # space-separated package list; change per environment without rebuilds
      # Example packages from WP Packagist:
      # - wpackagist-plugin/woocommerce:^9
      # - wpackagist-plugin/wp-mail-smtp:^4
      # - wpackagist-plugin/disable-xml-rpc:*
      COMPOSER_REQUIRE: ${COMPOSER_REQUIRE:-}
      # Optional JSON to add extra repos/config:
      # COMPOSER_JSON_EXTRAS: '{"config":{"allow-plugins":{"composer/installers": true}}}'
      COMPOSER_JSON_EXTRAS: ${COMPOSER_JSON_EXTRAS:-}
      TARGET_DIR: /opt/vendor
      CONTENT_DIR: /opt/wp-content
    volumes:
      - wp_vendor:/opt/vendor
      - wp_content:/opt/wp-content
    command: [ "bash", "-lc", "true" ]  # entrypoint handles everything
    restart: "no"

  wordpress:
    # build:
    #   context: .
    #   dockerfile: ./app.Dockerfile
    image: ghcr.io/kaffolder7/wordpress-immutable:latest
    depends_on:
      vendor:
        condition: service_completed_successfully
    environment:
      <<: *common_wordpress_env
    read_only: true  # Keep the container immutable at runtime
    tmpfs:
      - /tmp:size=64m,mode=1777
      - /var/run:size=16m
    volumes:
      # Read-only vendor tree produced by the builder
      - wp_vendor:/opt/vendor:ro
      # If you truly need no local writes at all, omit wp_files entirely and rely on S3 Uploads.
      # - wp_files:/var/www/html/wp-content  # (optional; consider mounting subdirs readonly)
      - wp_content:/var/www/html/wp-content:ro
    healthcheck:
      # test: ["CMD", "curl", "-sf", "http://127.0.0.1/healthz?t=${HEALTHZ_TOKEN}"]
      # test: ["CMD", "curl", "-fsS", "http://localhost/healthz.php"]
      test: ["CMD", "curl", "-fsS", "http://localhost/healthz.php?t=${HEALTHZ_TOKEN}"]
      interval: 15s  # 15–30s
      timeout: 3s  # 2–5s
      retries: 5  # 5-10
    deploy:
      resources:
        limits:
          memory: "768M"
    restart: unless-stopped
    stop_grace_period: 15s
    # Expose to your reverse proxy or Cloudflare Tunnel/LB; no direct 80/443 needed if proxied
    # ports:
    #   - "8080:80"

  # Example: managed DB elsewhere; this local MariaDB is only for demo/testing
  mariadb:
    image: mariadb:11
    profiles: ["dev"]
    environment:
      MARIADB_RANDOM_ROOT_PASSWORD: "true"
      MARIADB_DATABASE: ${WORDPRESS_DB_NAME:-wordpress}
      MARIADB_USER: ${WORDPRESS_DB_USER:-wp}
      MARIADB_PASSWORD: ${WORDPRESS_DB_PASSWORD:-changeme}
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  # (Optional)
  redis:
    image: redis:7-alpine
    command: ["redis-server", "--save", "", "--appendonly", "no"]  # pure cache
    healthcheck:
      test: ["CMD", "redis-cli", "PING"]
      interval: 10s
      timeout: 3s
      retries: 5

  # A tiny cron service so web `wordpress` workers never run cron work:
  cron:
    image: ghcr.io/kaffolder7/wordpress-immutable:latest
    depends_on:
      vendor:
        condition: service_completed_successfully
    environment:
      <<: *common_wordpress_env
      HEALTHZ_CHECK_REDIS: 0
      # Any extra defines you need the cron job to inherit
      # WORDPRESS_CONFIG_EXTRA: |
      #   define('DISABLE_WP_CRON', true);
    # Needs the same content to let wp-cli bootstrap with your mu-plugins/vendor
    volumes:
      - wp_vendor:/opt/vendor:ro
      - wp_content:/var/www/html/wp-content:ro
    read_only: true
    tmpfs:
      - /tmp:size=32m,mode=1777
      - /var/run:size=8m
    # Simple 60s loop; swap for a real scheduler if you prefer
    command: bash -lc 'while true; do wp cron event run --due-now --path=/var/www/html --allow-root --quiet || true; sleep 60; done'
    restart: unless-stopped
    stop_grace_period: 15s
    healthcheck:
      test: ["CMD-SHELL","wp cron event list --path=/var/www/html --allow-root >/dev/null 2>&1 || exit 1"]
      interval: 1m
      timeout: 5s
      retries: 3